import * as gridCell from "./gridCell.js";

export const walls = [
  { row: 0, column: 2, side: gridCell.RIGHT },
  { row: 0, column: 11, side: gridCell.RIGHT },
  { row: 1, column: 5, side: gridCell.LEFT },
  { row: 1, column: 5, side: gridCell.DOWN },
  { row: 2, column: 7, side: gridCell.RIGHT },
  { row: 2, column: 7, side: gridCell.DOWN },
  { row: 2, column: 11, side: gridCell.RIGHT },
  { row: 2, column: 11, side: gridCell.DOWN },
  { row: 3, column: 13, side: gridCell.UP },
  { row: 3, column: 13, side: gridCell.RIGHT },
  { row: 4, column: 0, side: gridCell.UP },
  { row: 4, column: 3, side: gridCell.RIGHT },
  { row: 4, column: 3, side: gridCell.DOWN },
  { row: 4, column: 10, side: gridCell.LEFT },
  { row: 4, column: 10, side: gridCell.DOWN },
  { row: 5, column: 6, side: gridCell.UP },
  { row: 5, column: 6, side: gridCell.LEFT },
  { row: 5, column: 12, side: gridCell.UP },
  { row: 5, column: 12, side: gridCell.LEFT },
  { row: 6, column: 1, side: gridCell.UP },
  { row: 6, column: 1, side: gridCell.RIGHT },
  { row: 6, column: 15, side: gridCell.UP },
  { row: 9, column: 3, side: gridCell.UP },
  { row: 9, column: 3, side: gridCell.RIGHT },
  { row: 9, column: 12, side: gridCell.LEFT },
  { row: 9, column: 12, side: gridCell.UP },
  { row: 10, column: 10, side: gridCell.DOWN },
  { row: 10, column: 10, side: gridCell.RIGHT },
  { row: 10, column: 15, side: gridCell.UP },
  { row: 11, column: 1, side: gridCell.LEFT },
  { row: 11, column: 1, side: gridCell.DOWN },
  { row: 12, column: 6, side: gridCell.DOWN },
  { row: 12, column: 6, side: gridCell.RIGHT },
  { row: 12, column: 14, side: gridCell.UP },
  { row: 12, column: 14, side: gridCell.RIGHT },
  { row: 13, column: 0, side: gridCell.DOWN },
  { row: 14, column: 2, side: gridCell.LEFT },
  { row: 14, column: 2, side: gridCell.UP },
  { row: 14, column: 11, side: gridCell.LEFT },
  { row: 14, column: 11, side: gridCell.DOWN },
  { row: 15, column: 5, side: gridCell.RIGHT },
  { row: 15, column: 13, side: gridCell.RIGHT },
];

export const targets = [
  { row: 1, column: 5, color: gridCell.BLUE_TARGET, shape: gridCell.CRICLE_TARGET },
  { row: 2, column: 7, color: gridCell.WILD_TARGET, shape: gridCell.VORTEX_TARGET },
  { row: 2, column: 11, color: gridCell.RED_TARGET, shape: gridCell.SQUARE_TARGET },
  { row: 3, column: 13, color: gridCell.YELLOW_TARGET, shape: gridCell.CRICLE_TARGET },
  { row: 4, column: 3, color: gridCell.RED_TARGET, shape: gridCell.HEXAGON_TARGET },
  { row: 4, column: 10, color: gridCell.GREEN_TARGET, shape: gridCell.HEXAGON_TARGET },
  { row: 5, column: 6, color: gridCell.GREEN_TARGET, shape: gridCell.SQUARE_TARGET },
  { row: 5, column: 12, color: gridCell.BLUE_TARGET, shape: gridCell.TRIANGLE_TARGET },
  { row: 6, column: 1, color: gridCell.YELLOW_TARGET, shape: gridCell.TRIANGLE_TARGET },
  { row: 9, column: 3, color: gridCell.YELLOW_TARGET, shape: gridCell.HEXAGON_TARGET },
  { row: 9, column: 12, color: gridCell.BLUE_TARGET, shape: gridCell.HEXAGON_TARGET },
  { row: 10, column: 10, color: gridCell.YELLOW_TARGET, shape: gridCell.SQUARE_TARGET },
  { row: 11, column: 1, color: gridCell.RED_TARGET, shape: gridCell.CRICLE_TARGET },
  { row: 12, column: 6, color: gridCell.BLUE_TARGET, shape: gridCell.SQUARE_TARGET },
  { row: 12, column: 14, color: gridCell.RED_TARGET, shape: gridCell.TRIANGLE_TARGET },
  { row: 14, column: 2, color: gridCell.GREEN_TARGET, shape: gridCell.TRIANGLE_TARGET },
  { row: 14, column: 11, color: gridCell.GREEN_TARGET, shape: gridCell.CRICLE_TARGET },
];
